let data = [
    { "movie": "Challengers", "year": 2024, "length": 132, "myScore": 4.5, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.6, "RottenTomatoes": 88, "rewatch": false, "heart": false },
    { "movie": "The Idea of You", "year": 2023, "length": 120, "myScore": 2.0, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 85, "rewatch": false , "heart": false},
    { "movie": "Civil War", "year": 2023, "length": 140, "myScore": 3.5, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 6.8, "RottenTomatoes": 80, "rewatch": false , "heart": false},
    { "movie": "Gone Girl", "year": 2014, "length": 149, "myScore": 4.5, "letterBoxAvg": 4.3, "oscars": 0, "imdbScore": 8.1, "RottenTomatoes": 88, "rewatch": false, "heart": true },
    { "movie": "Dune: Part 2", "year": 2023, "length": 160, "myScore": 4.0, "letterBoxAvg": 4.6, "oscars": 0, "imdbScore": 8.2, "RottenTomatoes": 84, "rewatch": false , "heart": true},
    { "movie": "Dune", "year": 2021, "length": 155, "myScore": 5.0, "letterBoxAvg": 4.4, "oscars": 6, "imdbScore": 8.1, "RottenTomatoes": 83, "rewatch": true , "heart": false},
    { "movie": "9 to 5", "year": 1980, "length": 110, "myScore": 4.5, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 6.9, "RottenTomatoes": 83, "rewatch": true , "heart": true},
    { "movie": "Bottoms", "year": 2023, "length": 92, "myScore": 4.0, "letterBoxAvg": 3.6, "oscars": 0, "imdbScore": 7.0, "RottenTomatoes": 75, "rewatch": false , "heart": true},
    { "movie": "Midsommar", "year": 2019, "length": 147, "myScore": 4.5, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.1, "RottenTomatoes": 83, "rewatch": true , "heart": false},
    { "movie": "Passages", "year": 2023, "length": 91, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 6.9, "RottenTomatoes": 78, "rewatch": false , "heart": false},
    { "movie": "Spider-Man: Into the Spider-Verse", "year": 2018, "length": 117, "myScore": 3.5, "letterBoxAvg": 4.5, "oscars": 1, "imdbScore": 8.4, "RottenTomatoes": 97, "rewatch": true , "heart": false},
    { "movie": "Rotting in the Sun", "year": 2023, "length": 104, "myScore": 4.0, "letterBoxAvg": 3.7, "oscars": 0, "imdbScore": 6.8, "RottenTomatoes": 74, "rewatch": false, "heart": false },
    { "movie": "Past Lives", "year": 2023, "length": 106, "myScore": 4.5, "letterBoxAvg": 4.4, "oscars": 0, "imdbScore": 8.0, "RottenTomatoes": 95, "rewatch": false, "heart": true },
    { "movie": "Whiplash", "year": 2014, "length": 106, "myScore": 3.0, "letterBoxAvg": 4.4, "oscars": 3, "imdbScore": 8.5, "RottenTomatoes": 94, "rewatch": false, "heart": true },
    { "movie": "The Menu", "year": 2022, "length": 107, "myScore": 2.0, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.5, "RottenTomatoes": 89, "rewatch": false , "heart": true},
    { "movie": "How to Blow Up a Pipeline", "year": 2022, "length": 103, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.3, "RottenTomatoes": 88, "rewatch": false, "heart": false },
    { "movie": "Anatomy of a Fall", "year": 2023, "length": 150, "myScore": 4.5, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.9, "RottenTomatoes": 87, "rewatch": false, "heart": true },
    { "movie": "Killers of the Flower Moon", "year": 2023, "length": 206, "myScore": 4.5, "letterBoxAvg": 4.6, "oscars": 0, "imdbScore": 8.1, "RottenTomatoes": 92, "rewatch": false, "heart": true },
    { "movie": "May December", "year": 2023, "length": 113, "myScore": 4.0, "letterBoxAvg": 3.5, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 80, "rewatch": false , "heart": true},
    { "movie": "Zone of Interest", "year": 2023, "length": 105, "myScore": 5.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.8, "RottenTomatoes": 85, "rewatch": false , "heart": false},
    { "movie": "Everything Everywhere All at Once", "year": 2022, "length": 140, "myScore": 4.0, "letterBoxAvg": 4.5, "oscars": 7, "imdbScore": 8.0, "RottenTomatoes": 91, "rewatch": false, "heart": false },
    { "movie": "Poor Things", "year": 2023, "length": 141, "myScore": 4.4, "letterBoxAvg": 5.0, "oscars": 0, "imdbScore": 7.6, "RottenTomatoes": 85, "rewatch": false, "heart": true },
    { "movie": "First Reformed", "year": 2017, "length": 113, "myScore": 4.3, "letterBoxAvg": 5.0, "oscars": 0, "imdbScore": 7.1, "RottenTomatoes": 93, "rewatch": false, "heart": true },
    { "movie": "The Grand Budapest Hotel", "year": 2014, "length": 99, "myScore": 2.0, "letterBoxAvg": 4.2, "oscars": 4, "imdbScore": 8.1, "RottenTomatoes": 92, "rewatch": false, "heart": true },
    { "movie": "Dumb Money", "year": 2023, "length": 104, "myScore": 3.5, "letterBoxAvg": 2.5, "oscars": 0, "imdbScore": 7.0, "RottenTomatoes": 75, "rewatch": false, "heart": true },
    { "movie": "Inception", "year": 2010, "length": 148, "myScore": 5.0, "letterBoxAvg": 4.5, "oscars": 4, "imdbScore": 8.8, "RottenTomatoes": 87, "rewatch": true , "heart": true },
    { "movie": "Red Eye", "year": 2005, "length": 85, "myScore": 3.5, "letterBoxAvg": 3.5, "oscars": 0, "imdbScore": 6.5, "RottenTomatoes": 79, "rewatch": false, "heart": true },
    { "movie": "Fight Club", "year": 1999, "length": 139, "myScore": 3.5, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 8.8, "RottenTomatoes": 79, "rewatch": true, "heart": true },
    { "movie": "Pulp Fiction", "year": 1994, "length": 154, "myScore": 4.5, "letterBoxAvg": 4.0, "oscars": 1, "imdbScore": 8.9, "RottenTomatoes": 94, "rewatch": true, "heart": true },
    { "movie": "Jeane Dielman, 23, quai du Commerce, 1080 Bruxelles", "year": 1975, "length": 201, "myScore": 4.5, "letterBoxAvg": 4.3, "oscars": 0, "imdbScore": 7.8, "RottenTomatoes": 89, "rewatch": false, "heart": true },
    { "movie": "All of Us Strangers", "year": 2023, "length": 105, "myScore": 4.0, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 78, "rewatch": false, "heart": false },
    { "movie": "Saltburn", "year": 2023, "length": 127, "myScore": 2.5, "letterBoxAvg": 3.8, "oscars": 0, "imdbScore": 7.0, "RottenTomatoes": 73, "rewatch": false, "heart": true },
    { "movie": "The Holdovers", "year": 2023, "length": 133, "myScore": 3.5, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.3, "RottenTomatoes": 81, "rewatch": false, "heart": true },
    { "movie": "Barbie", "year": 2023, "length": 114, "myScore": 4.0, "letterBoxAvg": 3.8, "oscars": 0, "imdbScore": 7.5, "RottenTomatoes": 90, "rewatch": false , "heart": true},
    { "movie": "Oppenheimer", "year": 2023, "length": 180, "myScore": 4.5, "letterBoxAvg": 4.6, "oscars": 0, "imdbScore": 8.4, "RottenTomatoes": 94, "rewatch": false , "heart": true},
    { "movie": "No Hard Feelings", "year": 2023, "length": 103, "myScore": 2.5, "letterBoxAvg": 3.6, "oscars": 0, "imdbScore": 6.8, "RottenTomatoes": 72, "rewatch": false, "heart": true },
    { "movie": "Air", "year": 2023, "length": 112, "myScore": 2.5, "letterBoxAvg": 3.7, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 85, "rewatch": false, "heart": true },
    { "movie": "Magic Mike: Last Dance", "year": 2023, "length": 112, "myScore": 3.5, "letterBoxAvg": 3.4, "oscars": 0, "imdbScore": 5.7, "RottenTomatoes": 55, "rewatch": false, "heart": true },
    { "movie": "Babylon", "year": 2022, "length": 188, "myScore": 3.0, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 55, "rewatch": false, "heart": true },
    { "movie": "Red", "year": 1994, "length": 111, "myScore": 4.0, "letterBoxAvg": 3.8, "oscars": 0, "imdbScore": 7.0, "RottenTomatoes": 72, "rewatch": false, "heart": true },
    { "movie": "White", "year": 1994, "length": 105, "myScore": 4.5, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 6.7, "RottenTomatoes": 77, "rewatch": false, "heart": true },
    { "movie": "Blue", "year": 1993, "length": 98, "myScore": 4.5, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 8.0, "RottenTomatoes": 83, "rewatch": false, "heart": true },
    { "movie": "M3gan", "year": 2022, "length": 102, "myScore": 3.5, "letterBoxAvg": 3.7, "oscars": 0, "imdbScore": 6.4, "RottenTomatoes": 93, "rewatch": false, "heart": true },
    { "movie": "Falling for Christmas", "year": 2022, "length": 95, "myScore": 1.0, "letterBoxAvg": 2.9, "oscars": 0, "imdbScore": 5.3, "RottenTomatoes": 50, "rewatch": false, "heart": true },
    { "movie": "The Woman King", "year": 2022, "length": 135, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 6.9, "RottenTomatoes": 94, "rewatch": false, "heart": true },
    { "movie": "Bros", "year": 2022, "length": 115, "myScore": 3.8, "letterBoxAvg": 2.0, "oscars": 0, "imdbScore": 6.4, "RottenTomatoes": 88, "rewatch": false, "heart": true },
    { "movie": "The Banshees of Inisherin", "year": 2022, "length": 114, "myScore": 4.0, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.8, "RottenTomatoes": 97, "rewatch": false, "heart": true },
    { "movie": "Don't Worry Darling", "year": 2022, "length": 123, "myScore": 3.5, "letterBoxAvg": 3.6, "oscars": 0, "imdbScore": 6.2, "RottenTomatoes": 38, "rewatch": false, "heart": true },
    { "movie": "Bones and All", "year": 2022, "length": 130, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 6.8, "RottenTomatoes": 82, "rewatch": false, "heart": true },
    { "movie": "Tar", "year": 2022, "length": 158, "myScore": 5.0, "letterBoxAvg": 4.3, "oscars": 0, "imdbScore": 7.5, "RottenTomatoes": 91, "rewatch": false, "heart": true },
    { "movie": "Room", "year": 2015, "length": 118, "myScore": 3.5, "letterBoxAvg": 4.3, "oscars": 1, "imdbScore": 8.1, "RottenTomatoes": 93, "rewatch": false, "heart": false },
    { "movie": "Nope", "year": 2022, "length": 130, "myScore": 4.5, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 6.9, "RottenTomatoes": 83, "rewatch": false, "heart": true },
    { "movie": "Elvis", "year": 2022, "length": 159, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 78, "rewatch": false, "heart": true },
    { "movie": "Aftersun", "year": 2022, "length": 101, "myScore": 4.5, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.7, "RottenTomatoes": 97, "rewatch": false, "heart": true },
    { "movie": "Top Gun: Maverick", "year": 2022, "length": 130, "myScore": 3.5, "letterBoxAvg": 4.5, "oscars": 0, "imdbScore": 8.3, "RottenTomatoes": 96, "rewatch": false, "heart": true },
    { "movie": "Matrix: Resurrections", "year": 2021, "length": 148, "myScore": 3.5, "letterBoxAvg": 3.4, "oscars": 0, "imdbScore": 5.7, "RottenTomatoes": 63, "rewatch": false, "heart": true },
    { "movie": "Interstellar", "year": 2014, "length": 169, "myScore": 4.0, "letterBoxAvg": 4.6, "oscars": 1, "imdbScore": 8.6, "RottenTomatoes": 72, "rewatch": true, "heart": true },
    { "movie": "Don't Look Up", "year": 2021, "length": 138, "myScore": 3.0, "letterBoxAvg": 3.8, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 55, "rewatch": false, "heart": true },
    { "movie": "Licorice Pizza", "year": 2021, "length": 133, "myScore": 3.5, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.3, "RottenTomatoes": 91, "rewatch": false, "heart": true },
    { "movie": "House of Gucci", "year": 2021, "length": 158, "myScore": 3.5, "letterBoxAvg": 3.7, "oscars": 0, "imdbScore": 6.6, "RottenTomatoes": 61, "rewatch": false , "heart": true},
    { "movie": "Encanto", "year": 2021, "length": 102, "myScore": 4.5, "letterBoxAvg": 4.1, "oscars": 1, "imdbScore": 7.3, "RottenTomatoes": 91, "rewatch": false, "heart": false },
    { "movie": "The Babadook", "year": 2014, "length": 30, "myScore": 4.0, "letterBoxAvg": 3.0, "oscars": 0, "imdbScore": 8.0, "RottenTomatoes": 98, "rewatch": true, "heart": true },
    { "movie": "Triangle of Sadness", "year": 2022, "length": 147, "myScore": 5.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.6, "RottenTomatoes": 71, "rewatch": false, "heart": true },
    { "movie": "The Northman", "year": 2022, "length": 137, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.1, "RottenTomatoes": 89, "rewatch": false, "heart": true },
    { "movie": "The Batman", "year": 2022, "length": 176, "myScore": 3.0, "letterBoxAvg": 4.5, "oscars": 0, "imdbScore": 7.8, "RottenTomatoes": 85, "rewatch": false, "heart": true },
    { "movie": "Cha Cha Real Smooth", "year": 2022, "length": 107, "myScore": 3.5, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.3, "RottenTomatoes": 85, "rewatch": false, "heart": true },
    { "movie": "The Green Knight", "year": 2021, "length": 130, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 6.8, "RottenTomatoes": 89, "rewatch": false, "heart": true },
    { "movie": "The Worst Person in the World", "year": 2021, "length": 128, "myScore": 3.5, "letterBoxAvg": 4.4, "oscars": 0, "imdbScore": 7.9, "RottenTomatoes": 96, "rewatch": false, "heart": true },
    { "movie": "I Care a Lot", "year": 2020, "length": 118, "myScore": 4.0, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 6.3, "RottenTomatoes": 79, "rewatch": false, "heart": true },
    { "movie": "Tenet", "year": 2020, "length": 150, "myScore": 4.0, "letterBoxAvg": 4.2, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 69, "rewatch": false , "heart": false},
    { "movie": "Fight Club", "year": 1999, "length": 139, "myScore": 3.5, "letterBoxAvg": 4.6, "oscars": 0, "imdbScore": 8.8, "RottenTomatoes": 79, "rewatch": false, "heart": false },
    { "movie": "Palm Springs", "year": 2020, "length": 90, "myScore": 3.5, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 95, "rewatch": false , "heart": false},
    { "movie": "Zola", "year": 2020, "length": 90, "myScore": 4.0, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 6.5, "RottenTomatoes": 90, "rewatch": false, "heart": true },
    { "movie": "Arrival", "year": 2016, "length": 116, "myScore": 4.5, "letterBoxAvg": 4.4, "oscars": 1, "imdbScore": 7.9, "RottenTomatoes": 94, "rewatch": true, "heart": true, "heart": true },
    { "movie": "Little Women", "year": 2019, "length": 135, "myScore": 4.0, "letterBoxAvg": 4.4, "oscars": 1, "imdbScore": 7.9, "RottenTomatoes": 95, "rewatch": false, "heart": true },
    { "movie": "The French Dispatch", "year": 2021, "length": 108, "myScore": 2.5, "letterBoxAvg": 4.0, "oscars": 0, "imdbScore": 7.2, "RottenTomatoes": 75, "rewatch": false, "heart": true },
    { "movie": "Nomadland", "year": 2020, "length": 108, "myScore": 2.5, "letterBoxAvg": 4.5, "oscars": 3, "imdbScore": 7.3, "RottenTomatoes": 93, "rewatch": false, "heart": true },
    { "movie": "Soul", "year": 2020, "length": 100, "myScore": 3.0, "letterBoxAvg": 4.4, "oscars": 2, "imdbScore": 8.1, "RottenTomatoes": 95, "rewatch": false,  "heart": true},
    { "movie": "Judas and the Black Messiah", "year": 2021, "length": 126, "myScore": 3.5, "letterBoxAvg": 4.2, "oscars": 2, "imdbScore": 7.5, "RottenTomatoes": 96, "rewatch": false, "heart": false },
    { "movie": "Sound of Metal", "year": 2019, "length": 120, "myScore": 4.5, "letterBoxAvg": 4.3, "oscars": 2, "imdbScore": 7.8, "RottenTomatoes": 96, "rewatch": false, "heart": false },
    { "movie": "The Lighthouse", "year": 2019, "length": 109, "myScore": 4.0, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.5, "RottenTomatoes": 90, "rewatch": false , "heart": false},
    { "movie": "Portrait of a Lady on Fire", "year": 2019, "length": 122, "myScore": 4.5, "letterBoxAvg": 4.7, "oscars": 0, "imdbScore": 8.1, "RottenTomatoes": 98, "rewatch": false, "heart": false },
    { "movie": "The Irishman", "year": 2019, "length": 209, "myScore": 3.5, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.9, "RottenTomatoes": 95, "rewatch": false , "heart": false},
    { "movie": "Marriage Story", "year": 2019, "length": 137, "myScore": 3.5, "letterBoxAvg": 4.3, "oscars": 0, "imdbScore": 7.9, "RottenTomatoes": 94, "rewatch": false, "heart": true },
    { "movie": "1917", "year": 2019, "length": 119, "myScore": 3.5, "letterBoxAvg": 4.5, "oscars": 3, "imdbScore": 8.3, "RottenTomatoes": 89, "rewatch": false, "heart": true },
    { "movie": "Once Upon a Time in Hollywood", "year": 2019, "length": 161, "myScore": 3.5, "letterBoxAvg": 4.4, "oscars": 2, "imdbScore": 7.6, "RottenTomatoes": 85, "rewatch": false, "heart": true },
    { "movie": "Jojo Rabbit", "year": 2019, "length": 108, "myScore": 3.5, "letterBoxAvg": 4.2, "oscars": 1, "imdbScore": 7.9, "RottenTomatoes": 80, "rewatch": false, "heart": true },
    { "movie": "The Farewell", "year": 2019, "length": 100, "myScore": 4.0, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.5, "RottenTomatoes": 98, "rewatch": false , "heart": false},
    { "movie": "BlacKkKlansman", "year": 2018, "length": 135, "myScore": 4.0, "letterBoxAvg": 4.3, "oscars": 1, "imdbScore": 7.5, "RottenTomatoes": 96, "rewatch": false, "heart": false },
    { "movie": "A Star is Born", "year": 2018, "length": 136, "myScore": 4.0, "letterBoxAvg": 4.2, "oscars": 1, "imdbScore": 7.6, "RottenTomatoes": 89, "rewatch": false, "heart": false },
    { "movie": "Roma", "year": 2018, "length": 135, "myScore": 4.5, "letterBoxAvg": 4.5, "oscars": 3, "imdbScore": 7.7, "RottenTomatoes": 96, "rewatch": false, "heart": false },
    { "movie": "Parasite", "year": 2019, "length": 132, "myScore": 5.0, "letterBoxAvg": 4.6, "oscars": 4, "imdbScore": 8.6, "RottenTomatoes": 99, "rewatch": false, "heart": false },
    { "movie": "Lady Bird", "year": 2017, "length": 93, "myScore": 4.5, "letterBoxAvg": 4.3, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 99, "rewatch": true, "heart": false },
    { "movie": "The Shape of Water", "year": 2017, "length": 123, "myScore": 3.3, "letterBoxAvg": 4.2, "oscars": 4, "imdbScore": 7.3, "RottenTomatoes": 92, "rewatch": false, "heart": false },
    { "movie": "The Disaster Artist", "year": 2017, "length": 104, "myScore": 3.0, "letterBoxAvg": 3.9, "oscars": 0, "imdbScore": 7.4, "RottenTomatoes": 91, "rewatch": false, "heart": true },
    { "movie": "Moonlight", "year": 2016, "length": 111, "myScore": 4.5, "letterBoxAvg": 4.4, "oscars": 3, "imdbScore": 7.4, "RottenTomatoes": 98, "rewatch": true, "heart": false, "heart": true },
    { "movie": "Manchester by the Sea", "year": 2016, "length": 137, "myScore": 4.0, "letterBoxAvg": 4.3, "oscars": 2, "imdbScore": 7.8, "RottenTomatoes": 95, "rewatch": false, "heart": false },
    { "movie": "Get Out", "year": 2017, "length": 104, "myScore": 4.5, "letterBoxAvg": 4.4, "oscars": 1, "imdbScore": 7.7, "RottenTomatoes": 98, "rewatch": false, "heart": false },
    { "movie": "La La Land", "year": 2016, "length": 128, "myScore": 3.5, "letterBoxAvg": 4.3, "oscars": 6, "imdbScore": 8.0, "RottenTomatoes": 91, "rewatch": false, "heart": false },
    { "movie": "Knives Out", "year": 2019, "length": 130, "myScore": 3.5, "letterBoxAvg": 4.1, "oscars": 0, "imdbScore": 7.9, "RottenTomatoes": 97, "rewatch": false, "heart": false },
];
